# Default values for tutor-multi-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

clusterDomain: "*"

# Email address used for receiving Let's encrypt notifications if cert-manager
# is enabled.
notificationEmail: null

ingress-nginx:
  # Use ingress-nginx as a default controller.
  enabled: true

cert-manager:
  # Use cert-manager as a default certificate controller.
  enabled: true

# Configuration for the metrics server chart
metricsserver:
   # Control the chart inclusion
   enabled: false
   # See https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/values.yaml
   # for all available options

# Configuration for the Vertical Pod Autoscaler chart
vpa:
   # Control the chart inclusion
   enabled: false
   # See https://github.com/cowboysysop/charts/blob/master/charts/vertical-pod-autoscaler/values.yaml
   # for all available options

# Multi-tenant ElasticSearch
elasticsearch:
  enabled: false

# Multi-tenant OpenSearch
opensearch:
  enabled: false

# Configuration for the Karpenter chart
karpenter:
  # add Karpenter node management for AWS EKS clusters. See: https://karpenter.sh/
  enabled: false

# Prometheus stack
#   
# If no storage is defined, the Prometheus and Grafana data is stored on
# empheral storage. You can find more information about storages in the
# Prometheus operator user guides: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
# 
# - To make Grafana persistent, you may want to set Grafana storage as shown in https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L999-L1009
# - To set Prometheus storage, you can see the example storage spec at https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L3557-L3570
prometheusstack:
  enabled: false

# Configuration for the K8s Dashboard chart
k8sdashboard:
  enabled: false

# Before enablin Velero, make sure to execute "velero install --crds-only" to install
# the CRDs in the cluster.
velero:
  enabled: false

openfaas:
  enabled: false

vector:
  enabled: false

cluster-autoscaler:
  enabled: false
  # The following values are the default values for the cluster-autoscaler chart.
  # For more information on the values, please visit https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/values.yaml
